language:
  - cpp

before_install:
 - sudo pip install gcovr
 - wget --no-check-certificate -O ./cpputest-3.7.1.zip https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.7.1.zip?raw=true
 - unzip cpputest-3.7.1.zip 
 - mv cpputest-3.7.1 cpputest
 - rm cpputest-3.7.1.zip 

 - cd cpputest/cpputest_build
 - autoreconf .. -i
 - ../configure
 - make
 - cp -R ./lib ../

script:
 - cd $TRAVIS_BUILD_DIR/cpputest/examples
 - make CPPUTEST_USE_GCOV=Y clean all_no_tests 
 - ./CppUTestExamples_tests -o junit -v
 - gcovr --root ../.. --filter ".*examples.*" --exclude ".*AllTests.*" -x -o coverage.xml
 
after_script:  
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace [Tests]cpputest_*.xml coverage.xml $TESTSPACE_TOKEN/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
