language:
 - cpp

env:
 global:
  - CPPUTEST_HOME=$TRAVIS_BUILD_DIR/cpputest-3.8

before_install:
 - mkdir -p $HOME/bin
 - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
 - testspace config url samples.testspace.com
 - testspace -v
 - pip install --user gcovr
 - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.zip
 - unzip cpputest-3.8.zip

install:
 - pushd $CPPUTEST_HOME/cpputest_build
 - autoreconf .. -i
 - ../configure
 - make
 - cp -R ./lib ../
 - popd

script:
 - make -C $CPPUTEST_HOME/examples CPPUTEST_USE_GCOV=Y clean all_no_tests |& tee build.log ; test ${PIPESTATUS[0]} -eq 0
 - $CPPUTEST_HOME/examples/CppUTestExamples_tests -o junit -v
 - gcovr --root ./ --filter ".*examples/ApplicationLib/.*" -x -o coverage.xml

after_script:
 - testspace build.log{lint} [Tests]cpputest_*.xml coverage.xml 