language:
 - cpp

env:
 - CPPUTEST_HOME=$PWD/cpputest-3.8

before_install:
 - sudo pip install gcovr
 - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.zip
 - unzip cpputest-3.8.zip

install:
 - pushd $CPPUTEST_HOME/cpputest/cpputest_build
 - autoreconf .. -i
 - ../configure
 - make
 - cp -R ./lib ../
 - popd

script:
 - make -C $CPPUTEST_HOME/examples CPPUTEST_USE_GCOV=Y clean all_no_tests |& tee build.log ; test ${PIPESTATUS[0]} -eq 0
 - $CPPUTEST_HOME/examples/CppUTestExamples_tests -o junit -v
 - gcovr --root ./ --filter ".*examples/ApplicationLib/.*" -x -o coverage.xml

after_script:  
 - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
 - testspace build.log{issues} [Tests]cpputest_*.xml coverage.xml $TESTSPACE_TOKEN/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
