language:
  - cpp

before_install:
# Install system prerequisites
 - sudo pip install gcovr
 - ./testspace_install.sh
 - export PATH="${HOME}/testspace:${PATH}"
 
# Install CppUTest framework  
 - wget --no-check-certificate -O ./cpputest-3.7.1.zip https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.7.1.zip?raw=true
 - unzip cpputest-3.7.1.zip 
 - mv cpputest-3.7.1 cpputest
 - rm cpputest-3.7.1.zip 
 - cd cpputest/cpputest_build
 - autoreconf .. -i
 - ../configure
 - make
 - cp -R ./lib ../

script:
# Build the CppUTest examples
 - cd $TRAVIS_BUILD_DIR/cpputest/examples
 - make CPPUTEST_USE_GCOV=Y clean all_no_tests 
 - ./CppUTestExamples_tests -o junit -v
 - gcovr --root ../.. --filter ".*examples.*" --exclude ".*AllTests.*" -x -o coverage.xml
 
# Publish Test Results along with Coverage
 - testspace publish [Tests]cpputest_*.xml coverage.xml ${TESTSPACE_URL}
  