version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch-browsers
    steps:
      - checkout
      - run: "curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin"
      - run: "testspace config url samples.testspace.com"
      - run: "sudo pip install gcovr"
      - run: "wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.zip"
      - run: "unzip cpputest-3.8.zip"
      - run: cd cpputest-3.8/cpputest_build && autoreconf .. -i && ../configure && make && cp -R ./lib ../
      - run: make -C cpputest-3.8/examples CPPUTEST_USE_GCOV=Y clean all_no_tests |& tee build.log ; test ${PIPESTATUS[0]} -eq 0
      - run: cpputest-3.8/examples/CppUTestExamples_tests -o junit -v
      - run: gcovr --root ./ --filter ".*/ApplicationLib/.*" -x -o coverage.xml
      - run:
          name: Send reports to testspace
          command: "testspace build.log{lint} [Tests]cpputest_*.xml coverage.xml"
          when: always
